### ISSUE TITLE
New fb data quirks

### ISSUE THREAD

**Issue by Alexander-Weinberg** [dmhacker/facebook-message-analysis#3]
Hi this is an amazing tool!

I just used it today and wanted to let you know two small edits I had to make (Python3 on mac).
The first is to chang the name of the json bit and the second is to then adjust from milliseconds to seconds. After that it works great. 

38.     return sorted(copied_messages, key=lambda message : message['timestamp_ms'])

69.         date = datetime.datetime.fromtimestamp(message['timestamp_ms'] / 1000)

Best,
Alex

**Comment by dmhacker** [comment]
Fixed with #2 and #4. :)
